
import { Product, SubscriptionPlan } from '../types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Organic Whole Milk',
    category: 'Milk',
    price: 3.99,
    description: 'Fresh, organic whole milk sourced from grass-fed cows. Rich in calcium and vitamin D.',
    image: '/placeholder.svg',
    nutrition: {
      calories: 150,
      protein: 8,
      fat: 8,
      carbs: 12,
    },
    isPopular: true,
  },
  {
    id: '2',
    name: 'Low-Fat Yogurt',
    category: 'Yogurt',
    price: 2.49,
    description: 'Creamy low-fat yogurt with active cultures for digestive health.',
    image: '/placeholder.svg',
    nutrition: {
      calories: 120,
      protein: 10,
      fat: 2.5,
      carbs: 15,
    },
    isPopular: true,
  },
  {
    id: '3',
    name: 'Salted Butter',
    category: 'Butter',
    price: 4.29,
    description: 'Premium salted butter made from cream of grass-fed cows.',
    image: '/placeholder.svg',
    nutrition: {
      calories: 100,
      protein: 0.1,
      fat: 11,
      carbs: 0,
    },
    isPopular: false,
  },
  {
    id: '4',
    name: 'Cheddar Cheese Block',
    category: 'Cheese',
    price: 5.99,
    description: 'Aged cheddar cheese block, perfect for sandwiches and cooking.',
    image: '/placeholder.svg',
    nutrition: {
      calories: 120,
      protein: 7,
      fat: 10,
      carbs: 0.5,
    },
    isPopular: true,
  },
  {
    id: '5',
    name: 'Fresh Paneer',
    category: 'Paneer',
    price: 6.49,
    description: 'Freshly made paneer cheese, ideal for Indian dishes and salads.',
    image: '/placeholder.svg',
    nutrition: {
      calories: 130,
      protein: 8,
      fat: 11,
      carbs: 1,
    },
    isPopular: false,
  },
  {
    id: '6',
    name: 'Pure Ghee',
    category: 'Ghee',
    price: 8.99,
    description: 'Pure clarified butter made through traditional methods.',
    image: '/placeholder.svg',
    nutrition: {
      calories: 120,
      protein: 0,
      fat: 14,
      carbs: 0,
    },
    isPopular: true,
  },
  {
    id: '7',
    name: 'Fresh Cream',
    category: 'Cream',
    price: 3.79,
    description: 'Fresh pasteurized cream, perfect for desserts and cooking.',
    image: '/placeholder.svg',
    nutrition: {
      calories: 100,
      protein: 1,
      fat: 10,
      carbs: 2,
    },
    isPopular: false,
  },
  {
    id: '8',
    name: 'Vanilla Ice Cream',
    category: 'Ice Cream',
    price: 5.49,
    description: 'Creamy vanilla ice cream made with real vanilla beans.',
    image: '/placeholder.svg',
    nutrition: {
      calories: 180,
      protein: 3,
      fat: 9,
      carbs: 22,
    },
    isPopular: true,
  },
  {
    id: '9',
    name: 'Buttermilk',
    category: 'Buttermilk',
    price: 2.29,
    description: 'Traditional buttermilk, great for baking and drinking.',
    image: '/placeholder.svg',
    nutrition: {
      calories: 80,
      protein: 8,
      fat: 2,
      carbs: 10,
    },
    isPopular: false,
  },
];

export const subscriptionPlans: SubscriptionPlan[] = [
  {
    id: 'daily',
    name: 'Daily Essentials',
    description: 'Fresh dairy products delivered to your door every morning.',
    price: 9.99,
    duration: 'daily',
  },
  {
    id: 'weekly',
    name: 'Weekly Package',
    description: 'Get your dairy weekly with our most popular subscription plan.',
    price: 59.99,
    duration: 'weekly',
  },
  {
    id: 'monthly',
    name: 'Monthly Bundle',
    description: 'Our best value option with monthly delivery and extra savings.',
    price: 199.99,
    duration: 'monthly',
  },
];

export const categories = [
  'All',
  'Milk',
  'Yogurt',
  'Butter',
  'Cheese',
  'Paneer',
  'Ghee',
  'Cream',
  'Ice Cream',
  'Buttermilk',
];

export const dairyQuotes = [
  "A day without dairy is like a day without sunshine.",
  "Cheese is milk's leap toward immortality.",
  "Life is better with a glass of milk.",
  "You can't buy happiness, but you can buy ice cream, which is pretty much the same thing.",
  "Keep calm and eat yogurt for a healthy gut.",
  "All you need is love and a little bit of butter.",
  "Milk - nature's perfect food.",
  "Good cheese comes to those who wait.",
];
